"""added version to bookmark

Revision ID: 70ab05faa8a3
Revises: 9a9a41f5a80f
Create Date: 2025-12-13 17:13:39.656044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ab05faa8a3'
down_revision: Union[str, Sequence[str], None] = '9a9a41f5a80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable
    op.add_column(
        'bookmark',
        sa.Column('version', sa.Integer(), nullable=True)
    )

    # 2. Backfill existing rows
    op.execute("UPDATE bookmark SET version = 1")

    # 3. Enforce NOT NULL
    op.alter_column(
        'bookmark',
        'version',
        nullable=False
    )

    # 4. (Optional) Default for future inserts
    op.alter_column(
        'bookmark',
        'version',
        server_default=sa.text("1")
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'version')
    # ### end Alembic commands ###
