"""added isfeatured  to bookmark

Revision ID: 95b19bfa64d0
Revises: 70ab05faa8a3
Create Date: 2026-01-14 13:19:58.354810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b19bfa64d0'
down_revision: Union[str, Sequence[str], None] = '70ab05faa8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable WITH a server default
    op.add_column(
        'bookmark',
        sa.Column(
            'is_featured',
            sa.Boolean(),
            nullable=True,
            server_default=sa.false()
        )
    )

    # 2. Backfill existing rows
    op.execute(
        "UPDATE bookmark SET is_featured = FALSE WHERE is_featured IS NULL"
    )

    # 3. Enforce NOT NULL
    op.alter_column(
        'bookmark',
        'is_featured',
        nullable=False
    )

    # 4. Create index
    op.create_index(
        op.f('ix_bookmark_is_featured'),
        'bookmark',
        ['is_featured'],
        unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmark_is_featured'), table_name='bookmark')
    op.drop_column('bookmark', 'is_featured')
    # ### end Alembic commands ###
