"""new changes

Revision ID: 9a9a41f5a80f
Revises: 6c90abe92fcf
Create Date: 2025-12-13 13:42:51.497749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9a41f5a80f'
down_revision: Union[str, Sequence[str], None] = '6c90abe92fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('deleted_by_device', sa.Uuid(), nullable=True))
    op.add_column('folder', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_folder_parent_id'), 'folder', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'folder', 'folder', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folder', type_='foreignkey')
    op.drop_index(op.f('ix_folder_parent_id'), table_name='folder')
    op.drop_column('folder', 'parent_id')
    op.drop_column('bookmark', 'deleted_by_device')
    # ### end Alembic commands ###
