"""add cover_image_url to bookmark

Revision ID: c78c1657eb40
Revises: 444f79e58625
Create Date: 2026-02-22 19:21:07.923937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78c1657eb40'
down_revision: Union[str, Sequence[str], None] = '444f79e58625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('cover_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'cover_image_url')
    # ### end Alembic commands ###
