"""Add user fields + refresh token table

Revision ID: cf9c9bec002b
Revises: 
Create Date: 2025-12-09 14:15:29.863092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9c9bec002b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    
    
    # --- Add new columns to User table ---
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
    op.add_column('user', sa.Column('reset_token', sa.String(), nullable=True))
    op.create_index('ix_user_reset_token', 'user', ['reset_token'], unique=False)
    op.add_column('user', sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))
    
    
    #refresh table
    op.create_table('refreshtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refreshtoken_jti'), 'refreshtoken', ['jti'], unique=True)
    op.create_index(op.f('ix_refreshtoken_user_id'), 'refreshtoken', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- Drop indexes and columns from User ---
    op.drop_index('ix_user_reset_token', table_name='user')
    op.drop_column('user', 'reset_token_expires_at')
    op.drop_column('user', 'reset_token')
    op.drop_column('user', 'is_deleted')
    op.drop_column('user', 'is_active')
    
    #for refresh table
    op.drop_index(op.f('ix_refreshtoken_user_id'), table_name='refreshtoken')
    op.drop_index(op.f('ix_refreshtoken_jti'), table_name='refreshtoken')
    op.drop_table('refreshtoken')
    # ### end Alembic commands ###
