"""changed bookmark model fk

Revision ID: efa25d824c3d
Revises: d1b7b389bab9
Create Date: 2026-01-14 22:33:31.614780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa25d824c3d'
down_revision: Union[str, Sequence[str], None] = 'd1b7b389bab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookmark_last_modified_device_fkey'), 'bookmark', type_='foreignkey')
    op.create_foreign_key(None, 'bookmark', 'device', ['last_modified_device'], ['device_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookmark', type_='foreignkey')
    op.create_foreign_key(op.f('bookmark_last_modified_device_fkey'), 'bookmark', 'device', ['last_modified_device'], ['id'])
    # ### end Alembic commands ###
